<?php
$this->title = 'Удаление статуса';
$this->headTitle($this->title);
?>
<p>Вы действительно хотите удалить статус <?php echo $this->escape($this->status['status']); ?></p>
<form method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'delete-status')); ?>">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->status['id']; ?>" />
        <input type="submit" name="delete" value="yes" />
        <input type="submit" name="delete" value="no" />
    </div>
</form>