<?php
$this->title = 'Удаление аудитории';
$this->headTitle($this->title);
?>
<p>Вы действительно хотите удалить аудиторию <?php echo $this->escape($this->classroom['number']); ?></p>
<form method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'delete-classroom')); ?>">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->classroom['id']; ?>" />
        <input type="submit" name="delete" value="yes" />
        <input type="submit" name="delete" value="no" />
    </div>
</form>