<?php
    echo $this->message;
    $this->title = 'Раздел данных';
    $this->headTitle($this->title);
?>
<ul class="">
    <li class=""><a href="<?php echo $this->url(array('controller'=>'data', 'action'=>'get-all-classrooms')) ?>">Аудитории</a></li>
    <li class=""><a href="<?php echo $this->url(array('controller'=>'data', 'action'=>'get-all-statuses')) ?>">Статусы</a></li>
    <li class=""><a href="<?php echo $this->url(array('controller'=>'data', 'action'=>'get-all-subjects')) ?>">Предметы</a></li>
    <li class=""><a href="<?php echo $this->url(array('controller'=>'data', 'action'=>'get-all-specialisations')) ?>">Специальности</a></li>
</ul>