<?php
//header('Content-type: text/html; charset=utf-8');
echo $this->doctype();
$auth = Zend_Auth::getInstance();
?>
<html>
<head>
    <?php
    echo $this->headTitle();
    echo $this->headMeta();    
    echo $this->headLink();
    echo $this->headScript();
    ?>
</head>
<body>
    <div id="logo">
        <h1 id="l">L</h1>
        <h1 id="e">e</h1>
        <h1 id="v">v</h1>
        <h1 id="ee">e</h1>
        <h1 id="ll">l</h1>
        <h1 class="big">U</h1>
        <h1 class="big">P</h1>         
    </div>
    <div id="head">        
        <ul class="">
            <div id="personal">
            <?php if ($auth->hasIdentity()){ ?>
                <li>
                    <form action="<?php echo $this->url(array('controller'=>'user', 'action'=>'get-info')); ?>">
                        <input type="hidden" value="<?php echo $auth->getIdentity()->idUsersInfo ;?>" name="id"/>
                        <input type="submit" class="butAsL" title="Мой профиль" value="<?php echo $auth->getIdentity()->usersLogin ;?>" />
                    </form><br /><br /><br />
                    <form action="<?php echo $this->url(array('controller'=>'user', 'action'=>'logout')); ?>">
                        <input type="submit" class="butAsL" value="Выйти" />
                    </form>
                </li>
                </div>
            <div id="controls">
                    <li><a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'index')) ?>">Смотреть пользователей</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'add')) ?>">Добавить пользователя</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'students', 'action'=>'index')) ?>">Смотреть студентов</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'students', 'action'=>'add')) ?>">Добавить студента</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'pars', 'action'=>'index')) ?>" id="ico">Добавить студентов</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'data', 'action'=>'index')) ?>">Перейти к разделу данных</a></li>
                </div>
            <?php } else { ?>
                <li><a href="<?php echo $this->url(array(), 'user-login') ?>" id="login">Войти</a></li>
            <?php } ?>
        </ul>
    </div>
    <div id="content">
        <?php
        echo $this->layout()->content;
        ?>
    </div>
    <div id="up"><a href="http://levelup.dp.ua/" target="_blank" title="На LevelUP"></a></div>
</body>
</html>