<?php
$this->title = 'Просмотр студента';
$this->headTitle($this->title);
$student = $this->student;
$group = new Application_Model_DbTable_Groups();
$nameGroup = $group->getGroup($student['idGroup']);
?>

<p>Вы смотрите студента: </p>
'Имя'<h3><?php echo $this->escape($student['nameStudent']); ?></h3>
'Фамилия'<h3><?php echo $this->escape($student['lastNameStudent']); ?></h3>
'Фамилия заказчика'<h3><?php echo $this->escape($student['lastNameCustomer']); ?></h3>
'Группа'<h3><?php echo $nameGroup['name']; ?></h3>
'Номер договора'<h3><?php echo $this->escape($student['numberContract']); ?></h3>