<?php
$this->title = 'Просмотр студента';
$this->headTitle($this->title);
$student = $this->student;
$group = new Application_Model_DbTable_Groups();
$nameGroup = $group->getGroup($student['idGroup']);
?>

<p>Вы смотрите студента: </p>
<table class="info">
    <tr>
        <td><strong>Имя:</strong><td>
        <td><?php echo $this->escape($student['nameStudent']); ?><td>
    </tr>
    <tr>
        <td><strong>Фамилия:</strong><td>
        <td><?php echo $this->escape($student['lastNameStudent']); ?><td>
    </tr>
    <tr>
        <td><strong>Фамилия заказчика:</strong><td>
        <td><?php echo $this->escape($student['lastNameCustomer']); ?><td>
    </tr>
    <tr>
        <td><strong>Группа:</strong><td>
        <td><?php echo $nameGroup['name']; ?><td>
    </tr>
    <tr>
        <td><strong>Номер договора:</strong><td>
        <td><?php echo $this->escape($student['numberContract']); ?><td>
    </tr>
</table>
<p class="fakeL">Назад</p>