<?php if (count($this->students)) { ?>


    <table  class="sortable">
        <thead>
        <tr>            
            <th>Фамилия Имя</th>            
            <th>Группа</th>
            <th>Моб. телефон</th>
            <th>Email</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->PartialLoop('/partials/students-row.phtml', $this->students) ?>
        </tbody>
    </table>
<?php } else { ?>
    <div>
        Нет студентов
    </div>
<?php } ?>