<?php
$this->title = ' Просмотр пользователя';
$this->headTitle($this->title);
$user = $this->usersInfo['user'];
$loginPass = $this->usersInfo['loginPass'];
$role = $this->usersInfo['role'];
$status = $this->usersInfo['status'];
?>

<p>Вы смотрите пользователя: </p>
<table class="info">
    <tr>
        <td><strong>Имя:</strong><td>
        <td><?php echo $this->escape($user['firstName']); ?><td>
    </tr>
    <tr>
        <td><strong>Фамилия:</strong><td>
        <td><?php echo $this->escape($user['lastName']); ?><td>
    </tr>
    <tr>
        <td><strong>Роль:</strong><td>
        <td><?php echo $this->escape($role['usersRole']); ?><td>
    </tr>
    <tr>
        <td><strong>Статус:</strong><td>
        <td><?php echo $this->escape($status['status']); ?><td>
    </tr>
    <tr>
        <td><strong>Логин:</strong><td>
        <td><?php echo $this->escape($loginPass['usersLogin']); ?><td>
    </tr>
</table>

<h6>Вернуться к просмотру:</h6>
<p class="fakeL">Назад</p>