<?php if (count($this->users)) { ?>


    <table>
        <thead>
        <tr>
            <th>UserId</th>
            <th>Role</th>
            <th>UserName</th>
            <th>UserEmail</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->PartialLoop('/partials/users-row.phtml', $this->users) ?>
        </tbody>
    </table>
<?php } else { ?>
    <div>
        Нет пользователей
    </div>
<?php } ?>