<?php if (count($this->users)) { ?>


    <table class="sortable">
        <thead>
        <tr>            
            <th>Фамилия Имя</th>
            <th>Роль</th>
            <th>Email</th>
            <th>Телефон</th>
        </tr>
        </thead>
        <tbody>
        <?php echo $this->PartialLoop('/partials/users-row.phtml', $this->users) ?>
        </tbody>
    </table>
<?php } else { ?>
    <div>
        Нет пользователей
    </div>
<?php } ?>