<tr>
    <td><?php echo $this->number ?></td>
    <td><?php echo $this->description ?></td>

    <td>
        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'get-classroom')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="showClassroom" value="Смотреть" />
                <i class="look" title="Смотреть"></i>
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'get-schedule-by-classroom')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="showSchedule" value="Расписание" />
                <i class="schedule" title="Расписание"></i>
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'edit-classroom')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="editClassroom" value="Редактировать" />
                <i class="edit" title="Редактировать"></i>
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'delete-classroom')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="deleteClassroom" value="Удалить" />
                <i class="cut" title="Удалить"></i>
            </label>
        </form>
    </td>
</tr>