<tr>
    <td><?php echo $this->specialisation ?></td>
    <td><?php echo $this->specDurations ?></td>

    <td>
        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'edit-specialisation')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="editSpecialisation" value="Редактировать" />
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'delete-specialisation')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="deleteSpecialisation" value="Удалить" />
            </label>
        </form>
    </td>
</tr>