<tr>
    <td><?php echo $this->id ?></td>
    <td><?php echo $this->status ?></td>

    <td>
        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'edit-status')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="editStatus" value="Редактировать" />
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'delete-status')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="deleteStatus" value="Удалить" />
            </label>
        </form>
    </td>
</tr>