<tr>
    <?php
    $group = new Application_Model_DbTable_Groups();
    $currentGroup = $group->getGroup($this->idGroup);
    ?>

    <td><?php echo $this->id; ?></td>
    <td><?php echo $this->firstName; ?></td>
    <td><?php echo $this->lastName; ?></td>
    <td><?php echo $currentGroup['name']; ?></td>

    <td>
        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'get-info')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="showUser" value="Смотреть" />
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'get-schedule-by-user')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="showSchedule" value="Расписание" />
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'edit')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="editUser" value="Редактировать" />
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'delete')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="deleteUser" value="Удалить" />
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'students', 'action'=>'add-payment')); ?>">
            <input type="hidden" name="idStudent" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="addPayment" value="Внести платеж" />
            </label>
        </form>
    </td>
</tr>