<tr>
    <?php
    $group = new Application_Model_DbTable_Groups();
    $currentGroup = $group->getGroup($this->idGroup);
    ?>

    <td><?php echo $this->id; ?></td>
    <td><?php echo $this->nameStudent; ?></td>
    <td><?php echo $this->lastNameStudent; ?></td>
    <td><?php echo $currentGroup['name']; ?></td>

    <td>
        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'students', 'action'=>'get-info')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="showStudent" value="Смотреть" />
                <i class="look" title="Смотреть"></i>
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'students', 'action'=>'edit')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="editStudent" value="Редактировать" />
                <i class="edit" title="Редактировать"></i>
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'students', 'action'=>'delete')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="deleteStudent" value="Удалить" />
                <i class="cut" title="Удалить"></i>
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'students', 'action'=>'add-payment')); ?>">
            <input type="hidden" name="idStudent" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="addPayment" value="Внести платеж" />
                <i class="payment" title="Внести платеж"></i>
            </label>
        </form>
    </td>
</tr>