<tr>
    <?php
    $role = new Application_Model_DbTable_UsersRole();
    $usersRole = $role->getUsersRole($this->idUsersRole);
    ?>

    <td><?php echo $this->id; ?></td>
    <td><?php echo $usersRole['usersRole']; ?></td>
    <td><?php echo $this->firstName; ?></td>
    <td><?php echo $this->email; ?></td>

    <td>
        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'get-info')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="showUser" value="Смотреть" />
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'get-schedule-by-user')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="showSchedule" value="Расписание" />
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'edit')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="editUser" value="Редактировать" />
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'delete')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="" type="submit" name="deleteUser" value="Удалить" />
            </label>
        </form>
    </td>
</tr>