<tr>
    <?php
    $role = new Application_Model_DbTable_UsersRole();
    $usersRole = $role->getUsersRole($this->idUsersRole);
    
    const PHOTO_PATH = '/img/photos/users/';
    ?>
    
    <td class="text_img" data-img="<?php echo PHOTO_PATH. $this->photo; ?>"><?php echo $this->lastName .' '. $this->firstName; ?></td>
    <td><?php echo $usersRole['usersRole']; ?></td>
    <td><?php echo $this->email; ?></td>
    <td><?php echo $this->phone; ?></td>

    <td>
        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'get-info')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />            
            <label>
                <input class="hidden" type="submit" name="showUser" value="Смотреть" />
                <i class="look" title="Смотреть"></i>
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'data', 'action'=>'get-schedule-by-user')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="showSchedule" value="Расписание" />
                <i class="schedule" title="Расписание"></i>
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'edit')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="editUser" value="Редактировать" />
                <i class="edit" title="Редактировать"></i>
            </label>
        </form>

        <form class="" method="POST" action="<?php echo $this->url(array('controller'=>'user', 'action'=>'delete')); ?>">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
            <label>
                <input class="hidden" type="submit" name="deleteUser" value="Удалить" />
                <i class="cut" title="Удалить"></i>
            </label>
        </form>
    </td>
</tr>